spring.application.name=mongo-playground-1

spring.data.mongodb.uri=mongodb://localhost:27017/ex_base_16_backend
spring.data.mongodb.database=ex_base_16_backend
spring.mongodb.uri=mongodb://localhost:27017/ex_base_16_backend
spring.mongodb.database=ex_base_16_backend
